server:
  port: 8083

spring:
  profiles:
    active: dev # 로컬(dev) / git(prod)

---
# 로컬(dev) 환경 설정
spring:
  config:
    activate:
      on-profile: dev

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---
# 프로덕션(prod) 환경 설정
spring:
  config:
    activate:
      on-profile: prod

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://challet.world:8761/eureka

---
# 공통 설정
spring:
  config:
    import: application-key.yml
  application:
    name: kb-bank
  datasource:
    url: jdbc:mysql://challet.world:${dbport}/kbbank-api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: challet
    password: ${mysqlpassword}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: api/kb-bank/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
