#server:
#  port: 8085

spring:
  profiles:
    active: prod # 로컬(dev) / git(prod)

---
# 로컬(dev) 환경 설정
spring:
  config:
    activate:
      on-profile: dev
    import: application-key.yml

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

---
# 프로덕션(prod) 환경 설정
spring:
  config:
    activate:
      on-profile: prod
    import: "classpath:/application-key.yml"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://challet-discovery-spring:8761/eureka
---
# 공통 설정
spring:
  application:
    name: sh-bank
  datasource:
    url: jdbc:mysql://challet.world:${dbport}/shbank-api?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: challet
    password: ${mysqlpassword}
    hikari:
      maximum-pool-size: 30  # 최대 30개의 연결
      minimum-idle: 10       # 최소 10개의 유휴 연결
      idle-timeout: 30000    # 30초 동안 유휴 상태일 때 연결을 닫음
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  elasticsearch:
    uris: "challet.world:9200"


springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: api/sh-bank/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

jwt:
  secret: ${jwt_secret_key}
  access-exp: ${jwt_access_exp}
  refresh-exp: ${jwt_refresh_exp}

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
